== Configuring the Elasticsearch Client
[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `elasticsearch` feature to configure the https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html[ElasticsearchClient^] in your project:
----
$ mn create-app my-app --features elasticsearch
----
====

To configure the https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html[ElasticsearchClient^] you should first add `elasticsearch` module to your classpath:

[source,groovy]
.build.gradle
----
implementation("io.micronaut.elasticsearch:micronaut-elasticsearch")
----

You should then configure the `httpHosts` of the Elasticsearch server you wish to communicate with in `application.yml` as:

[source,yaml]
.application.yml
----
elasticsearch:
  httpHosts: "http://localhost:9200,http://127.0.0.2:9200"
----

See the API for api:.elasticsearch.DefaultElasticsearchConfigurationProperties[] for more information on the available configuration options.

Once you have the above configuration in place then you can inject the `co.elastic.clients.elasticsearch.ElasticsearchClient`, the `co.elastic.clients.elasticsearch.ElasticsearchAsyncClient` or the `org.elasticsearch.client.RestClient` bean. The following is the simplest way to get Elasticsearch information using the ElasticsearchClient:

[source,groovy]
----
include::test-suite-groovy/src/test/groovy/io/micronaut/docs/configuration/elasticsearch/ElasticsearchSpec.groovy[tags=query,indent=0]
----

<1> `client` is an instance of the `co.elastic.clients.elasticsearch.ElasticsearchClient` bean.

For more information on executing different operations using ElasticsearchClient please read the https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html[Elasticsearch Documentation^].

== Modify the Default Request Configurations

Often times you want to change the default configurations. To achieve this Micronaut, includes the ability to change the default request configurations. You can set the default request configurations under key `elasticsearch.request.default` as:

[source,yaml]
.application.yml
----
elasticsearch:
  httpHosts: http://localhost:9200,http://127.0.0.2:9200
  request:
    default:
      expectContinueEnabled: true
      localAddress: 198.57.151.22
----

See the API https://hc.apache.org/httpcomponents-client-5.2.x/current/httpclient5/apidocs/org/apache/hc/client5/http/config/RequestConfig.Builder.html[RequestConfig.Builder^] for more information on the available configuration options.

== Modify the HTTP Client Configurations

To modify the HTTP Client configurations (e.g. request timeouts, authentication, or anything that the https://hc.apache.org/httpcomponents-client-5.1.x/current/httpclient5/apidocs/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.html[HttpAsyncClientBuilder^] allows to set). You can define a bean using https://docs.micronaut.io/latest/api/io/micronaut/context/annotation/Factory.html[Factory] which replaces `org.apache.http.impl.nio.client.HttpAsyncClientBuilder`.

Following is an example to change the default credentials provider:

[source,groovy]
----
include::test-suite-groovy/src/test/groovy/io/micronaut/docs/configuration/elasticsearch/ElasticsearchSpec.groovy[tags=httpClientFactoryImports,indent=0]
include::test-suite-groovy/src/test/groovy/io/micronaut/docs/configuration/elasticsearch/ElasticsearchSpec.groovy[tags=singletonImports,indent=0]
include::test-suite-groovy/src/test/groovy/io/micronaut/docs/configuration/elasticsearch/ElasticsearchSpec.groovy[tags=httpClientFactory,indent=0]
----

=== Logging

Elasticsearch uses log4j for logging but Micronaut uses slf4j with Logback. To make it work properly, add the following dependency:

dependency:org.slf4j:log4j-over-slf4j[version="1.7.30", scope="runtimeOnly"]
