plugins {
    id "io.micronaut.build.internal.elasticsearch-base"
    id "java-library"
}

tasks.named("test") {
    useJUnitPlatform()
    systemProperty("elasticsearch.version", libs.versions.managed.elasticsearch.get())
}

java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
